package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Checklist generated by hbm2java
 */
public class Checklist  implements java.io.Serializable {


     private BigDecimal id;
     private String nombre;
     private String descripcion;
     private Set listapreguntas = new HashSet(0);
     private Set respuestas = new HashSet(0);
     private Set cuestionarios = new HashSet(0);

    public Checklist() {
    }

	
    public Checklist(BigDecimal id, String nombre, String descripcion) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Checklist(BigDecimal id, String nombre, String descripcion, Set listapreguntas, Set respuestas, Set cuestionarios) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.listapreguntas = listapreguntas;
       this.respuestas = respuestas;
       this.cuestionarios = cuestionarios;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getListapreguntas() {
        return this.listapreguntas;
    }
    
    public void setListapreguntas(Set listapreguntas) {
        this.listapreguntas = listapreguntas;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }
    public Set getCuestionarios() {
        return this.cuestionarios;
    }
    
    public void setCuestionarios(Set cuestionarios) {
        this.cuestionarios = cuestionarios;
    }




}


