package app.modelo;
// Generated 04-11-2020 20:26:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Checklist generated by hbm2java
 */
public class Checklist  implements java.io.Serializable {


     private BigDecimal id;
     private Instancia instancia;
     private String nombre;
     private String descripcion;
     private Set preguntas = new HashSet(0);

    public Checklist() {
    }

	
    public Checklist(BigDecimal id, Instancia instancia, String nombre, String descripcion) {
        this.id = id;
        this.instancia = instancia;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Checklist(BigDecimal id, Instancia instancia, String nombre, String descripcion, Set preguntas) {
       this.id = id;
       this.instancia = instancia;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.preguntas = preguntas;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Instancia getInstancia() {
        return this.instancia;
    }
    
    public void setInstancia(Instancia instancia) {
        this.instancia = instancia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


