package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Cuestionario generated by hbm2java
 */
public class Cuestionario  implements java.io.Serializable {


     private BigDecimal id;
     private Checklist checklist;
     private Instancia instancia;

    public Cuestionario() {
    }

    public Cuestionario(BigDecimal id, Checklist checklist, Instancia instancia) {
       this.id = id;
       this.checklist = checklist;
       this.instancia = instancia;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Checklist getChecklist() {
        return this.checklist;
    }
    
    public void setChecklist(Checklist checklist) {
        this.checklist = checklist;
    }
    public Instancia getInstancia() {
        return this.instancia;
    }
    
    public void setInstancia(Instancia instancia) {
        this.instancia = instancia;
    }




}


