package app.modelo;
// Generated 04-11-2020 20:26:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private BigDecimal id;
     private String razonsocial;
     private Set instancias = new HashSet(0);
     private Set pagos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(BigDecimal id, String razonsocial) {
        this.id = id;
        this.razonsocial = razonsocial;
    }
    public Empresa(BigDecimal id, String razonsocial, Set instancias, Set pagos, Set usuarios) {
       this.id = id;
       this.razonsocial = razonsocial;
       this.instancias = instancias;
       this.pagos = pagos;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public Set getInstancias() {
        return this.instancias;
    }
    
    public void setInstancias(Set instancias) {
        this.instancias = instancias;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


