package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estadopago generated by hbm2java
 */
public class Estadopago  implements java.io.Serializable {


     private BigDecimal id;
     private String descripcion;
     private Set pagos = new HashSet(0);

    public Estadopago() {
    }

	
    public Estadopago(BigDecimal id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public Estadopago(BigDecimal id, String descripcion, Set pagos) {
       this.id = id;
       this.descripcion = descripcion;
       this.pagos = pagos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


