package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private BigDecimal id;
     private String nombre;
     private Set usuarios = new HashSet(0);

    public Estado() {
    }

	
    public Estado(BigDecimal id) {
        this.id = id;
    }
    public Estado(BigDecimal id, String nombre, Set usuarios) {
       this.id = id;
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


