package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Instancia generated by hbm2java
 */
public class Instancia  implements java.io.Serializable {


     private BigDecimal id;
     private Empresa empresa;
     private Estadoinstancia estadoinstancia;
     private Tipoinstancia tipoinstancia;
     private Usuario usuario;
     private String fechadesde;
     private String fechahasta;
     private String tema;
     private String descripcion;
     private String direccion;
     private Set cuestionarios = new HashSet(0);
     private Set respuestas = new HashSet(0);
     private Set registros = new HashSet(0);

    public Instancia() {
    }

	
    public Instancia(BigDecimal id, Empresa empresa, Estadoinstancia estadoinstancia, Tipoinstancia tipoinstancia, Usuario usuario, String fechadesde, String fechahasta, String tema, String descripcion, String direccion) {
        this.id = id;
        this.empresa = empresa;
        this.estadoinstancia = estadoinstancia;
        this.tipoinstancia = tipoinstancia;
        this.usuario = usuario;
        this.fechadesde = fechadesde;
        this.fechahasta = fechahasta;
        this.tema = tema;
        this.descripcion = descripcion;
        this.direccion = direccion;
    }
    public Instancia(BigDecimal id, Empresa empresa, Estadoinstancia estadoinstancia, Tipoinstancia tipoinstancia, Usuario usuario, String fechadesde, String fechahasta, String tema, String descripcion, String direccion, Set cuestionarios, Set respuestas, Set registros) {
       this.id = id;
       this.empresa = empresa;
       this.estadoinstancia = estadoinstancia;
       this.tipoinstancia = tipoinstancia;
       this.usuario = usuario;
       this.fechadesde = fechadesde;
       this.fechahasta = fechahasta;
       this.tema = tema;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.cuestionarios = cuestionarios;
       this.respuestas = respuestas;
       this.registros = registros;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Estadoinstancia getEstadoinstancia() {
        return this.estadoinstancia;
    }
    
    public void setEstadoinstancia(Estadoinstancia estadoinstancia) {
        this.estadoinstancia = estadoinstancia;
    }
    public Tipoinstancia getTipoinstancia() {
        return this.tipoinstancia;
    }
    
    public void setTipoinstancia(Tipoinstancia tipoinstancia) {
        this.tipoinstancia = tipoinstancia;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getFechadesde() {
        return this.fechadesde;
    }
    
    public void setFechadesde(String fechadesde) {
        this.fechadesde = fechadesde;
    }
    public String getFechahasta() {
        return this.fechahasta;
    }
    
    public void setFechahasta(String fechahasta) {
        this.fechahasta = fechahasta;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getCuestionarios() {
        return this.cuestionarios;
    }
    
    public void setCuestionarios(Set cuestionarios) {
        this.cuestionarios = cuestionarios;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


