package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion  implements java.io.Serializable {


     private BigDecimal id;
     private String nombre;
     private Set respuestas = new HashSet(0);

    public Opcion() {
    }

	
    public Opcion(BigDecimal id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Opcion(BigDecimal id, String nombre, Set respuestas) {
       this.id = id;
       this.nombre = nombre;
       this.respuestas = respuestas;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


