package app.modelo;
// Generated 04-11-2020 20:26:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion  implements java.io.Serializable {


     private BigDecimal id;
     private String nombre;
     private Set preguntas = new HashSet(0);

    public Opcion() {
    }

	
    public Opcion(BigDecimal id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Opcion(BigDecimal id, String nombre, Set preguntas) {
       this.id = id;
       this.nombre = nombre;
       this.preguntas = preguntas;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


