package app.modelo;
// Generated 04-11-2020 20:26:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Operacion generated by hbm2java
 */
public class Operacion  implements java.io.Serializable {


     private BigDecimal id;
     private Modulo modulo;
     private String nombre;
     private Set rolOperacions = new HashSet(0);

    public Operacion() {
    }

	
    public Operacion(BigDecimal id, Modulo modulo, String nombre) {
        this.id = id;
        this.modulo = modulo;
        this.nombre = nombre;
    }
    public Operacion(BigDecimal id, Modulo modulo, String nombre, Set rolOperacions) {
       this.id = id;
       this.modulo = modulo;
       this.nombre = nombre;
       this.rolOperacions = rolOperacions;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRolOperacions() {
        return this.rolOperacions;
    }
    
    public void setRolOperacions(Set rolOperacions) {
        this.rolOperacions = rolOperacions;
    }




}


