package app.modelo;
// Generated 04-11-2020 20:26:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private BigDecimal id;
     private Empresa empresa;
     private Estadopago estadopago;
     private String mesanio;
     private BigDecimal monto;
     private String fechadesde;
     private String fechahasta;

    public Pago() {
    }

    public Pago(BigDecimal id, Empresa empresa, Estadopago estadopago, String mesanio, BigDecimal monto, String fechadesde, String fechahasta) {
       this.id = id;
       this.empresa = empresa;
       this.estadopago = estadopago;
       this.mesanio = mesanio;
       this.monto = monto;
       this.fechadesde = fechadesde;
       this.fechahasta = fechahasta;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Estadopago getEstadopago() {
        return this.estadopago;
    }
    
    public void setEstadopago(Estadopago estadopago) {
        this.estadopago = estadopago;
    }
    public String getMesanio() {
        return this.mesanio;
    }
    
    public void setMesanio(String mesanio) {
        this.mesanio = mesanio;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getFechadesde() {
        return this.fechadesde;
    }
    
    public void setFechadesde(String fechadesde) {
        this.fechadesde = fechadesde;
    }
    public String getFechahasta() {
        return this.fechahasta;
    }
    
    public void setFechahasta(String fechahasta) {
        this.fechahasta = fechahasta;
    }




}


