package app.modelo;
// Generated 04-11-2020 20:26:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private BigDecimal id;
     private Checklist checklist;
     private Opcion opcion;
     private String pregunta;

    public Pregunta() {
    }

    public Pregunta(BigDecimal id, Checklist checklist, Opcion opcion, String pregunta) {
       this.id = id;
       this.checklist = checklist;
       this.opcion = opcion;
       this.pregunta = pregunta;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Checklist getChecklist() {
        return this.checklist;
    }
    
    public void setChecklist(Checklist checklist) {
        this.checklist = checklist;
    }
    public Opcion getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }




}


