package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private BigDecimal id;
     private String item;
     private Set respuestas = new HashSet(0);
     private Set listapreguntas = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(BigDecimal id, String item) {
        this.id = id;
        this.item = item;
    }
    public Pregunta(BigDecimal id, String item, Set respuestas, Set listapreguntas) {
       this.id = id;
       this.item = item;
       this.respuestas = respuestas;
       this.listapreguntas = listapreguntas;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }
    public Set getListapreguntas() {
        return this.listapreguntas;
    }
    
    public void setListapreguntas(Set listapreguntas) {
        this.listapreguntas = listapreguntas;
    }




}


