package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private BigDecimal id;
     private Instancia instancia;
     private String rut;
     private String nombre;
     private String cargo;
     private BigDecimal presente;

    public Registro() {
    }

    public Registro(BigDecimal id, Instancia instancia, String rut, String nombre, String cargo, BigDecimal presente) {
       this.id = id;
       this.instancia = instancia;
       this.rut = rut;
       this.nombre = nombre;
       this.cargo = cargo;
       this.presente = presente;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Instancia getInstancia() {
        return this.instancia;
    }
    
    public void setInstancia(Instancia instancia) {
        this.instancia = instancia;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public BigDecimal getPresente() {
        return this.presente;
    }
    
    public void setPresente(BigDecimal presente) {
        this.presente = presente;
    }




}


