package app.modelo;
// Generated 12-12-2020 19:24:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private BigDecimal id;
     private Checklist checklist;
     private Instancia instancia;
     private Opcion opcion;
     private Pregunta pregunta;
     private String fecha;

    public Respuesta() {
    }

    public Respuesta(BigDecimal id, Checklist checklist, Instancia instancia, Opcion opcion, Pregunta pregunta, String fecha) {
       this.id = id;
       this.checklist = checklist;
       this.instancia = instancia;
       this.opcion = opcion;
       this.pregunta = pregunta;
       this.fecha = fecha;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Checklist getChecklist() {
        return this.checklist;
    }
    
    public void setChecklist(Checklist checklist) {
        this.checklist = checklist;
    }
    public Instancia getInstancia() {
        return this.instancia;
    }
    
    public void setInstancia(Instancia instancia) {
        this.instancia = instancia;
    }
    public Opcion getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


