package app.modelo;
// Generated 04-11-2020 20:26:53 by Hibernate Tools 4.3.1



/**
 * RolOperacion generated by hbm2java
 */
public class RolOperacion  implements java.io.Serializable {


     private RolOperacionId id;
     private Operacion operacion;
     private Rol rol;

    public RolOperacion() {
    }

    public RolOperacion(RolOperacionId id, Operacion operacion, Rol rol) {
       this.id = id;
       this.operacion = operacion;
       this.rol = rol;
    }
   
    public RolOperacionId getId() {
        return this.id;
    }
    
    public void setId(RolOperacionId id) {
        this.id = id;
    }
    public Operacion getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(Operacion operacion) {
        this.operacion = operacion;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


