package app.modelo;
// Generated 04-11-2020 20:26:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private BigDecimal id;
     private Empresa empresa;
     private Estado estado;
     private Rol rol;
     private String username;
     private String password;
     private String nombres;
     private String apaterno;
     private String amaterno;
     private String rut;
     private String correo;
     private Set instancias = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(BigDecimal id, Empresa empresa, Estado estado, Rol rol, String username, String password, String nombres, String apaterno, String amaterno, String rut, String correo) {
        this.id = id;
        this.empresa = empresa;
        this.estado = estado;
        this.rol = rol;
        this.username = username;
        this.password = password;
        this.nombres = nombres;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.rut = rut;
        this.correo = correo;
    }
    public Usuario(BigDecimal id, Empresa empresa, Estado estado, Rol rol, String username, String password, String nombres, String apaterno, String amaterno, String rut, String correo, Set instancias) {
       this.id = id;
       this.empresa = empresa;
       this.estado = estado;
       this.rol = rol;
       this.username = username;
       this.password = password;
       this.nombres = nombres;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.rut = rut;
       this.correo = correo;
       this.instancias = instancias;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getInstancias() {
        return this.instancias;
    }
    
    public void setInstancias(Set instancias) {
        this.instancias = instancias;
    }




}


